version: "3"
services:
  nginx-0:
    container_name: nginx-0
    image: registry.saas.hand-china.com/tools/nginx:latest
    hostname: nginx-0
    ports:
    -  "8089:80"
    env: 
    - "MYSQL_ROOT_PASSWORD"="123456"
    - "mysql_ip"="123"
  nginx-1:
    container_name:nginx-1
    image:registry.saas.hand-china.com/tools/nginx:latest
    hostname:nginx-1
    ports:
    -  "8081:80"

